### ISSUE TITLE
Azure OpenAI Implementation

### ISSUE THREAD

**Issue by yesbhautik** [yesbhautik/Master-AI-BOT#28]
User have to configure:

----Model Type ----
MODEL TYPE=AzureOpenAI OR OpenAI

-if user selected OpenAI
OPENAI_API_KEY=

-else
---- For Text ----
AZURE_OPENAI_VERSION=
ENDPOINT=
KEY=

---- For Image ----
AZURE_OPENAI_VERSION=
ENDPOINT=
KEY=

---- For Voice ----
AZURE_OPENAI_VERSION=
ENDPOINT=
KEY=

Those key will be different if user want to use AzureOpenAI, because GPT-4 and DALL-E is not available in same region, same for whisper API.

**Comment by Luckydhingra** [comment]
i would like to work on it 
can u assign me ? nd add hacktoberfest label too

**Comment by yesbhautik** [comment]
Okay sureOn 31-Oct-2023 00:08, lucKy ***@***.***> wrote:
i would like to work on it
can u assign me ? nd add hacktoberfest label too

**Comment by yesbhautik** [comment]
I have added the label on #28.

**Comment by yesbhautik** [comment]
assigning #28 to @Luckydhingra
